version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    environment: ['xpack.security.enabled=false']
    ports: ['127.0.0.1:5601:5601']
    depends_on: ['elasticsearch']
